# -*- coding: utf-8 -*-
"""
/***************************************************************************
 OnlineMapLinker
                                 A QGIS plugin
 This plugin makes links from points to online map.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-07-17
        copyright            : (C) 2024 by Sanda Takeru
        email                : takeru_sanda999@maff.go.jp
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Sanda Takeru'
__date__ = '2024-07-17'
__copyright__ = '(C) 2024 by Sanda Takeru'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load OnlineMapLinker class from file OnlineMapLinker.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .online_map_linker import OnlineMapLinkerPlugin
    return OnlineMapLinkerPlugin()
